#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:/mapper/**/*.xml
#  type-aliases-package: com.yhjun.shopmall.board.vo, com.yhjun.shopmall.member.vo
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    password: 1111
    url: jdbc:log4jdbc:mysql://localhost:3306/shop_mall?characterEncoding=utf8
    username: root
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        "[show_sql]": true
        "[format_sql]": true
        "[use_sql_comments]": true       
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa